#!/usr/bin/env python3
"""
DataForge — Report Assembly Script

Assembles all generated artifacts into an HTML report and optionally a PDF.

Usage:
    python report.py \
        --output-dir <project_dir> \
        --project-name <name> \
        --problem-type <type> \
        --best-model <model_name> \
        --best-metric <metric_name> \
        --best-score <score>

Output:
    {output_dir}/reports/final_report.html
    {output_dir}/reports/final_report.pdf  (if WeasyPrint available)
"""
import argparse
import json
import sys
from pathlib import Path
from datetime import datetime


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DataForge Report — {project_name}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 0; background: #f8f9fa; color: #333; }}
  .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
             color: white; padding: 40px 60px; }}
  .header h1 {{ margin: 0; font-size: 2.2em; font-weight: 700; }}
  .header p {{ margin: 8px 0 0; opacity: 0.85; font-size: 1.05em; }}
  .badge {{ display: inline-block; background: rgba(255,255,255,0.2); border-radius: 20px;
            padding: 4px 14px; font-size: 0.85em; margin-top: 10px; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 30px 40px; }}
  .card {{ background: white; border-radius: 10px; padding: 28px 32px; margin-bottom: 24px;
           box-shadow: 0 2px 8px rgba(0,0,0,0.07); }}
  .card h2 {{ margin-top: 0; color: #1a1a2e; font-size: 1.35em; border-bottom: 2px solid #e9ecef; padding-bottom: 10px; }}
  .metric-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-top: 16px; }}
  .metric-box {{ background: #f8f9fa; border-radius: 8px; padding: 18px 20px; text-align: center; border: 1px solid #e9ecef; }}
  .metric-box .value {{ font-size: 2em; font-weight: 700; color: #0f3460; }}
  .metric-box .label {{ color: #666; font-size: 0.85em; margin-top: 4px; }}
  .best-badge {{ background: #0f3460; color: white; border-radius: 6px; padding: 2px 10px; font-size: 0.8em; margin-left: 8px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 14px; text-align: left; font-size: 0.9em; }}
  td {{ padding: 9px 14px; border-bottom: 1px solid #e9ecef; font-size: 0.9em; }}
  tr:hover {{ background: #f8f9fa; }}
  .rank-1 td {{ font-weight: 600; background: #fffbf0; }}
  img {{ max-width: 100%; height: auto; border-radius: 6px; margin-top: 12px; }}
  .img-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(420px, 1fr)); gap: 20px; }}
  .section-note {{ color: #666; font-size: 0.9em; margin: -8px 0 12px; }}
  .warning-box {{ background: #fff3cd; border: 1px solid #ffc107; border-radius: 6px; padding: 12px 16px; margin-bottom: 16px; }}
  .footer {{ text-align: center; color: #999; font-size: 0.82em; padding: 20px; border-top: 1px solid #e9ecef; }}
  pre {{ background: #f1f3f5; border-radius: 6px; padding: 14px; overflow-x: auto; font-size: 0.88em; }}
</style>
</head>
<body>

<div class="header">
  <h1>DataForge Report</h1>
  <p>Project: <strong>{project_name}</strong></p>
  <span class="badge">{problem_type}</span>
  <span class="badge">Generated: {generated_at}</span>
</div>

<div class="container">

  <!-- Summary -->
  <div class="card">
    <h2>Executive Summary</h2>
    <div class="metric-grid">
      <div class="metric-box">
        <div class="value">{best_model}</div>
        <div class="label">Best Model</div>
      </div>
      <div class="metric-box">
        <div class="value">{best_score}</div>
        <div class="label">{best_metric}</div>
      </div>
      <div class="metric-box">
        <div class="value">{n_rows:,}</div>
        <div class="label">Training Rows</div>
      </div>
      <div class="metric-box">
        <div class="value">{n_features}</div>
        <div class="label">Features</div>
      </div>
      <div class="metric-box">
        <div class="value">{n_models}</div>
        <div class="label">Models Compared</div>
      </div>
      <div class="metric-box">
        <div class="value">{deploy_target}</div>
        <div class="label">Deployment</div>
      </div>
    </div>
  </div>

  <!-- Model Leaderboard -->
  {leaderboard_section}

  <!-- EDA Section -->
  {eda_section}

  <!-- Interpretability Section -->
  {interpret_section}

  <!-- Visualizations Section -->
  {viz_section}

  <!-- How to Use -->
  <div class="card">
    <h2>How to Use This Model</h2>
    <pre>{usage_code}</pre>
  </div>

</div>

<div class="footer">
  Generated by DataForge — Autonomous Data Science Pipeline &nbsp;·&nbsp; {generated_at}
</div>

</body>
</html>
"""


def build_leaderboard_section(leaderboard_path: Path) -> str:
    if not leaderboard_path.exists():
        return ""
    try:
        with open(leaderboard_path) as f:
            lb = json.load(f)
    except Exception:
        return ""

    rows = ""
    for m in lb.get("models", []):
        rank = m["rank"]
        row_class = "rank-1" if rank == 1 else ""
        best_tag = '<span class="best-badge">BEST</span>' if rank == 1 else ""
        metrics_str = " | ".join(f"{k}: {v:.4f}" for k, v in m.get("metrics", {}).items()
                                 if isinstance(v, float) and not k.startswith("cv_"))
        rows += f'<tr class="{row_class}"><td>{rank}</td><td>{m["model"]}{best_tag}</td>' \
                f'<td>{m.get("primary_value", "—"):.4f}</td><td>{metrics_str}</td></tr>'

    img_tag = ""
    if lb.get("comparison_plot") and Path(lb["comparison_plot"]).exists():
        import base64
        with open(lb["comparison_plot"], "rb") as f:
            img_b64 = base64.b64encode(f.read()).decode()
        img_tag = f'<img src="data:image/png;base64,{img_b64}" alt="Model Comparison"/>'

    return f"""
  <div class="card">
    <h2>Model Leaderboard</h2>
    <p class="section-note">All models trained with 5-fold cross-validation on 80% of data, evaluated on 20% held-out test set.</p>
    <table>
      <tr><th>Rank</th><th>Model</th><th>{lb.get("primary_metric", "Score")}</th><th>Additional Metrics</th></tr>
      {rows}
    </table>
    {img_tag}
  </div>"""


def build_eda_section(reports_dir: Path) -> str:
    images = []
    for img_name in ["correlation_heatmap.png", "target_distribution.png", "missing_matrix.png"]:
        img_path = reports_dir / "eda" / img_name
        if img_path.exists():
            import base64
            with open(img_path, "rb") as f:
                img_b64 = base64.b64encode(f.read()).decode()
            title = img_name.replace(".png", "").replace("_", " ").title()
            images.append(f'<div><p><strong>{title}</strong></p>'
                          f'<img src="data:image/png;base64,{img_b64}" alt="{title}"/></div>')

    if not images:
        return ""

    grid = '<div class="img-grid">' + "".join(images) + "</div>"
    return f"""
  <div class="card">
    <h2>Exploratory Data Analysis</h2>
    {grid}
  </div>"""


def build_interpret_section(reports_dir: Path) -> str:
    images = []
    for img_name in ["shap_summary.png", "shap_bar.png", "feature_importance.png"]:
        img_path = reports_dir / img_name
        if img_path.exists():
            import base64
            with open(img_path, "rb") as f:
                img_b64 = base64.b64encode(f.read()).decode()
            title = img_name.replace(".png", "").replace("_", " ").title()
            images.append(f'<div><p><strong>{title}</strong></p>'
                          f'<img src="data:image/png;base64,{img_b64}" alt="{title}"/></div>')

    if not images:
        return ""

    grid = '<div class="img-grid">' + "".join(images) + "</div>"
    return f"""
  <div class="card">
    <h2>Model Interpretability (SHAP)</h2>
    <p class="section-note">SHAP values show the impact of each feature on individual predictions. Red = pushes prediction higher, Blue = lower.</p>
    {grid}
  </div>"""


def build_viz_section(reports_dir: Path) -> str:
    images = []
    for img_name in ["confusion_matrix.png", "roc_curve.png", "residual_plot.png", "pairplot.png"]:
        img_path = reports_dir / img_name
        if img_path.exists():
            import base64
            with open(img_path, "rb") as f:
                img_b64 = base64.b64encode(f.read()).decode()
            title = img_name.replace(".png", "").replace("_", " ").title()
            images.append(f'<div><p><strong>{title}</strong></p>'
                          f'<img src="data:image/png;base64,{img_b64}" alt="{title}"/></div>')

    if not images:
        return ""

    grid = '<div class="img-grid">' + "".join(images) + "</div>"
    return f"""
  <div class="card">
    <h2>Model Evaluation Plots</h2>
    {grid}
  </div>"""


def main():
    parser = argparse.ArgumentParser(description="DataForge report assembler")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--project-name", required=True)
    parser.add_argument("--problem-type", required=True)
    parser.add_argument("--best-model", default="unknown")
    parser.add_argument("--best-metric", default="score")
    parser.add_argument("--best-score", type=float, default=0.0)
    parser.add_argument("--deploy-target", default="streamlit")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    reports_dir = output_dir / "reports"
    models_dir = output_dir / "src" / "models"
    reports_dir.mkdir(parents=True, exist_ok=True)

    # Load project metadata
    config_path = output_dir / "dataforge.config.json"
    n_rows, n_features = 0, 0
    if config_path.exists():
        try:
            with open(config_path) as f:
                cfg = json.load(f)
            n_rows = cfg.get("dataset", {}).get("n_rows", 0)
            n_features = cfg.get("dataset", {}).get("n_features", 0)
        except Exception:
            pass

    leaderboard_path = models_dir / "leaderboard.json"
    n_models = 0
    if leaderboard_path.exists():
        try:
            with open(leaderboard_path) as f:
                lb = json.load(f)
            n_models = len(lb.get("models", []))
        except Exception:
            pass

    # Usage code example
    usage_code = f"""import joblib
import pandas as pd

# Load the best model
model = joblib.load("{args.output_dir}/src/models/{args.best_model}.pkl")

# Prepare your data (same preprocessing as training)
df = pd.read_csv("your_new_data.csv")
X = df.select_dtypes(include="number").fillna(0)

# Make predictions
predictions = model.predict(X)
probabilities = model.predict_proba(X)  # For classification

print(predictions)
"""

    # Build HTML sections
    leaderboard_section = build_leaderboard_section(leaderboard_path)
    eda_section = build_eda_section(reports_dir)
    interpret_section = build_interpret_section(reports_dir)
    viz_section = build_viz_section(reports_dir)

    html = HTML_TEMPLATE.format(
        project_name=args.project_name,
        problem_type=args.problem_type.replace("_", " ").title(),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        best_model=args.best_model,
        best_metric=args.best_metric.upper(),
        best_score=round(args.best_score, 4),
        n_rows=n_rows,
        n_features=n_features,
        n_models=n_models,
        deploy_target=args.deploy_target.title(),
        leaderboard_section=leaderboard_section,
        eda_section=eda_section,
        interpret_section=interpret_section,
        viz_section=viz_section,
        usage_code=usage_code,
    )

    html_path = reports_dir / "final_report.html"
    html_path.write_text(html, encoding="utf-8")
    print(f"HTML report saved: {html_path}")

    # Try PDF
    pdf_path = None
    try:
        import weasyprint
        pdf_path = reports_dir / "final_report.pdf"
        weasyprint.HTML(string=html).write_pdf(str(pdf_path))
        print(f"PDF report saved: {pdf_path}")
    except ImportError:
        print("Note: WeasyPrint not installed — HTML-only report generated.")
        print("Install with: pip install weasyprint")
    except Exception as e:
        print(f"Note: PDF generation failed ({e}) — HTML report available.")

    result = {
        "agent": "df-report",
        "status": "success",
        "html_path": str(html_path),
        "pdf_path": str(pdf_path) if pdf_path else None,
        "error": None,
    }
    print(json.dumps(result))


if __name__ == "__main__":
    main()
